server:
  port: 8000

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      routes:
        - id: public-user-service
          uri: lb://USER-SERVICE
          predicates:
            - name: Path
              args:
                patterns:
                  - /api/v1/users/signup
                  - /api/v1/users/login
                  - /api/v1/users/validate-token
                  - /api/v1/users/refresh-token
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - name: JwtAuthenticationFilter