server:
  port: 8080

spring:
  application:
    name: coupon-service
  datasource:
    url: jdbc:postgresql://localhost:5432/promotion
    driver-class-name: org.postgresql.Driver
    username: kid4211
    password: 12345678
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
  jpa:
    defer-datasource-initialization: true
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    org.hibernate.SQL: off
    org.hibernate.orm.jdbc.bind: off