services:
  postgres:
    image: postgres:17
    container_name: postgres-promotion
    restart: unless-stopped
    environment:
      POSTGRES_DB: promotion
      POSTGRES_USER: kid4211
      POSTGRES_PASSWORD: "12345678"
      TZ: Asia/Seoul
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - promotion_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kid4211 -d promotion"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7
    container_name: redis-promotion
    ports:
      - "6379:6379"
    volumes:
      - ./redis-config:/usr/local/etc/redis
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - promotion_network
  kafka:
    image: confluentinc/cp-kafka:7.5.1 # Apache Kafka 3.5.x = Confluent Platform 7.5.x
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # KRaft 필수 설정
      KAFKA_NODE_ID: 1  # 브로커 노드 ID
      CLUSTER_ID: 'EpwKlK0lR6qKZW0cGwZz8w'  # 클러스터 고유 식별자

      # 리스너 설정
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_LISTENERS: 'INTERNAL://:29092,EXTERNAL://:9092,CONTROLLER://:9093'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:29092,EXTERNAL://localhost:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'

      # KRaft 모드 설정
      KAFKA_PROCESS_ROLES: 'broker,controller'        # 브로커와 컨트롤러 역할 통합
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'  # 컨트롤러 쿼럼 설정
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'   # 컨트롤러 통신용 리스너

      # 복제 관련 설정
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0    # 로컬 리밸런스 지연 제거
    volumes:
      - ./data/kafka:/var/lib/kafka/data
    networks:
      - promotion_network
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "9090:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092  # 내부 리스너
    networks:
      - promotion_network    # 네트워크 추가
    depends_on:
      - kafka

networks: # 네트워크 정의 추가
  promotion_network:
    driver: bridge