server:
  port: 8004

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/promotion
    driver-class-name: org.postgresql.Driver
    username: kid4211
    password: 12345678
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

jwt:
  secret: 1ad35d74dc65cc0ee9a3a409f7f87e332aa6aa89d9cc64c66cdf9a1ffdc534ee

